### ISSUE TITLE
Maker issue

### ISSUE THREAD

**Issue by jmonroynieto** [CompSynBioLab-KoreaUniv/FunGAP#14]
Maker fails in all runs. this is the error message:

```
[Run] maker/2.31.9/bin/fasta_merge -d Tests/FunGAP/MAR_results/maker_out/H99/maker_run4/H99.maker.output/H99_master_datastore_index.log
ERROR: The file 'Tests/FunGAP/MAR_results/maker_out/H99/maker_run4/H99.maker.output/H99_master_datastore_index.log' does not exist
Traceback (most recent call last):
  File "miniconda/envs/fungap/bin/FunGAP/run_maker.py", line 647, in <module>
    main(sys.argv[1:])
  File "miniconda/envs/fungap/bin/FunGAP/run_maker.py", line 245, in main
    collect_result_final(input_fasta, output_dir, est_prefix)
  File "miniconda/envs/fungap/bin/FunGAP/run_maker.py", line 555, in collect_result_final
    copyfile(merged_gff3, output_gff3)
  File "miniconda/envs/fungap/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'Tests/FunGAP/MAR_results/maker_out/H99/maker_run4/H99.all.gff'
Traceback (most recent call last):
  File "miniconda/envs/fungap/bin/FunGAP/fungap.py", line 746, in <module>
    main(sys.argv[1:])
  File "miniconda/envs/fungap/bin/FunGAP/fungap.py", line 209, in main
    num_cores, repeat_model_file, trinity_asms, no_genemark_fungus
  File "miniconda/envs/fungap/bin/FunGAP/fungap.py", line 397, in run_maker
    check_call(command_args)
  File "/python/2.7.13/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'miniconda/envs/fungap/bin/FunGAP/run_maker.py', '--input_fasta', 'Tests/FunGAP/H99.fasta', '--augustus_species', 'cryptococcus_neoformans_neoformans_JEC21', '--protein_db_fasta', 'Tests/FunGAP/H99.faa', '--repeat_model', 'Tests/FunGAP/MAR_results/repeat_modeler_out/RM_15344.WedMar60925332019/consensi.fa.classified', '--est_files', 'Tests/FunGAP/MAR_results/trinity_out/trinity_H99/Trinity_H99.fasta', '--output_dir', 'Tests/FunGAP/MAR_results/maker_out', '--num_cores', '16', '--log_dir', 'Tests/FunGAP/MAR_results/logs', '--gmes_fungus']' returned non-zero exit status 1
```

Log maker_H99_run4.log:

```
Argument "2.56_01" isn't numeric in numeric ge (>=) at perl/5.24.1/lib/site_perl/5.24.1/x86_64-linux/forks.pm line 1570.
Possible precedence issue with control flow operator at perl/5.24.1/lib/site_perl/5.24.1/Bio/DB/IndexedBase.pm line 845.
STATUS: Parsing control files...
ERROR: The 'maker_gff' file[s] Tests/FunGAP/MAR_results/maker_out/H99/maker_run3/H99.all.gff do not exist.
Please check settings in the control files.

ERROR: The HMM file[s] provided for gmhmm do not exist:
	Tests/FunGAP/MAR_results/maker_out/genemark_out/output/gmhmm.mod
```

I noticed in issue #5, which appears to be similar, that one solution was to recompile Maker. My version 2.31.9 does not contain an /exe directory. I am therefore trying to recompile as per your instructions in that thread.

**Comment by mbnmbn00** [comment]
Because of the complexity of Maker installation, I adjusted the scripts to use Anaconda2.
But recent reports say we need to be careful when installing Maker via Anaconda2.

```
conda config --remove channels bioconda
conda config --remove channels conda-forge
conda config --add channels bioconda/label/cf201901
conda config --add channels conda-forge/label/cf201901
conda install maker
```

You also need to configure FunGAP (v1.1.0)

```
python set_dependencies.py \
  --pfam_db_dir db/pfam \
  --busco_db_dir db/busco/basidiomycota_odb9/ \
  --genemark_dir external/gm_et_linux_64/gmes_petap/ \
  --repeat_modeler_dir external/RepeatModeler-open-1.0.11
```

I think this is the easiest way to solve Maker issue.

**Comment by mbnmbn00** [comment]
Can you show me `maker_H99_run1.log`, too?

```
ERROR: The HMM file[s] provided for gmhmm do not exist:
	Tests/FunGAP/MAR_results/maker_out/genemark_out/output/gmhmm.mod
```
What this error message means is that GeneMark didn't run on your assembly. I think you may need to re-configure FunGAP.

**Comment by jmonroynieto** [comment]
`Argument "2.56_01" isn't numeric in numeric ge (>=) at /packages/perl/5.24.1/lib/site_perl/5.24.1/x86_64-linux/forks.pm line 1570.
Possible precedence issue with control flow operator at /packages/perl/5.24.1/lib/site_perl/5.24.1/Bio/DB/IndexedBase.pm line 845.
STATUS: Parsing control files...
ERROR: You have failed to provide a value for 'RepeatMasker' in the control files.

ERROR: You have failed to provide a value for 'exonerate' in the control files.`

**Comment by mbnmbn00** [comment]
Okay. Thank you for the sharing.
So when we run 'maker -CTL' command, it will automatically fill out for `RepeatMasker` and `exonerate`.
So I assume you don't have two executable in your `$PATH` variable.

I am not sure which FunGAP version you are using, but `RepeatMasker` and `exonerate` should be in your `$PATH` variable.

```
fungap.py --version   # I recommend it would be v1.1.0
which exonerate   # Check exonerate is executable
which RepeatMasker   # Check RepeatMasker is executable
```

Please follow the our installation guide:
https://github.com/CompSynBioLab-KoreaUniv/FunGAP/blob/master/INSTALL.md

**Comment by jmonroynieto** [comment]
The maker reinstallation pointed to this too, thank you.
