### ISSUE TITLE
braker1 error

### ISSUE THREAD

**Issue by ngrafgr** [CompSynBioLab-KoreaUniv/FunGAP#16]
This might be related with issue #3 but I still couldn't figure out my problem.  This is the log of my run:

```
[04-26 14:45] START: wrapper_run_braker1
[Wrapper] python /opt/fungap/1.1.0/run_braker1.py --masked_assembly /home/nathalia/aus58/OUTPUT/maker_out/masked_assembly.fasta --bam_files /home/nathalia/aus58/OUTPUT/hisat2_out/aus58.bam --output_dir /home/nathalia/aus58/OUTPUT/braker1_out --log_dir /home/nathalia/aus58/OUTPUT/logs --num_cores 32 --fungus
[04-26 14:45] START: BRAKER1
[Run] /opt/fungap/anaconda/bin/braker.pl --fungus --softmasking --cores=32 --genome=/home/nathalia/aus58/OUTPUT/maker_out/masked_assembly.fasta --bam=/home/nathalia/aus58/OUTPUT/hisat2_out/aus58.bam --species=aus58 --gff3 --AUGUSTUS_CONFIG_PATH=/opt/fungap/anaconda/bin/../config --BAMTOOLS_PATH=/opt/fungap/anaconda/bin --GENEMARK_PATH=/opt/fungap/1.1.0/external/gm_et_linux_64/gmes_petap --SAMTOOLS_PATH=/opt/fungap/anaconda/bin --workingdir=/home/nathalia/aus58/OUTPUT/braker1_out/aus58 > /home/nathalia/aus58/OUTPUT/logs/braker1/braker1_aus58.log 2>&1
Traceback (most recent call last):
  File "/opt/fungap/1.1.0/run_braker1.py", line 197, in <module>
    main(sys.argv[1:])
  File "/opt/fungap/1.1.0/run_braker1.py", line 91, in main
    masked_assembly, bam_files, output_dir, log_dir, num_cores, fungus_flag
  File "/opt/fungap/1.1.0/run_braker1.py", line 171, in run_braker1
    )[0],
IndexError: list index out of range
Check input files...
TRANS_READ_FILES is ok...
GENOME_ASSEMBLY is ok...
SISTER_PROTEOME is ok...

Traceback (most recent call last):
  File "/opt/fungap/1.1.0/fungap.py", line 746, in <module>
    main(sys.argv[1:])
  File "/opt/fungap/1.1.0/fungap.py", line 223, in main
    masked_assembly, trans_bams, output_dir, num_cores, no_braker_fungus
  File "/opt/fungap/1.1.0/fungap.py", line 446, in run_braker1
    check_call(command_args)
  File "/opt/fungap/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/opt/fungap/1.1.0/run_braker1.py', '--masked_assembly', '/home/nathalia/aus58/OUTPUT/maker_out/masked_assembly.fasta', '--bam_files', '/home/nathalia/aus58/OUTPUT/hisat2_out/aus58.bam', '--output_dir', '/home/nathalia/aus58/OUTPUT/braker1_out', '--log_dir', '/home/nathalia/aus58/OUTPUT/logs', '--num_cores', '32', '--fungus']' returned non-zero exit status 1
```

I checked braker errors in `(...)/OUTPUT/braker1_out/aus58/braker/aus58/errors` and the last file was `new_species.stderr`, and this was the error: `Environment variable AUGUSTUS_CONFIG_PATH not set. at /opt/fungap/anaconda/bin/new_species.pl line 48.`

I searched for `/opt/fungap/anaconda/bin/new_species.pl` and it does not exist in my directory. 

Many thanks!

**Comment by mbnmbn00** [comment]
If the `AUGUSTUS_CONFIG_PATH` is the issue,

> Environment variable AUGUSTUS_CONFIG_PATH not set. at /opt/fungap/anaconda/bin/new_species.pl line 48.

You may check conda install:
```
conda install augustus rmblast maker trinity hisat2 braker busco blast pfam_scan
pip install biopython bcbio-gff networkx markdown2 matplotlib
cpanm Hash::Merge Logger::Simple Parallel::ForkManager YAML
```

This will automatically set that variable.

You should double-check if the `AUGUSTUS_CONFIG_PATH` is defined by typing:
```
> echo $AUGUSTUS_CONFIG_PATH
/global/homes/m/mbnmbn00/anaconda2/envs/augustus/config/
```

**Comment by ngrafgr** [comment]
I checked the conda installation, and the variable was not set automatically. In fact, the `(...)/anaconda/envs/` is empty.

**Comment by mbnmbn00** [comment]
Could you show me the output of?
`> conda info --envs`

**Comment by ngrafgr** [comment]
```
 $  conda info --envs
# conda environments:
#
base                  *  /opt/fungap/anaconda
```

**Comment by mbnmbn00** [comment]
It looks no environment was set.

Could you follow these?
```
> conda update conda
> conda create -n fungap
> conda activate fungap
> conda config --remove channels bioconda
> conda config --remove channels conda-forge
> conda config --add channels bioconda/label/cf201901
> conda config --add channels conda-forge/label/cf201901
> conda install augustus rmblast maker trinity hisat2 braker busco blast pfam_scan
> pip install biopython bcbio-gff networkx markdown2 matplotlib
> cpanm Hash::Merge Logger::Simple Parallel::ForkManager YAML
```

And could you show me the output of:
```
> conda info --envs
> echo $AUGUSTUS_CONFIG_PATH
```

**Comment by ngrafgr** [comment]
Got it!
```
 $  conda info --envs
# conda environments:
#
base                  *  /opt/fungap/anaconda
fungap                   /opt/fungap/anaconda/envs/fungap
$  echo $AUGUSTUS_CONFIG_PATH
/opt/fungap/anaconda/config/
```

**Comment by mbnmbn00** [comment]
Hi,

Based on your outputs, I think you installed the modules outside fungap environment.
It should be

```
/opt/fungap/anaconda/**fungap**/config/
```

where `fungap` is environment name.

You may run below command before installing the modules.

```
> conda activate fungap
```

Otherwise, when you install other programs using `conda`, that might mess up the settings.
Likewise, you should activate fungap environment for running FunGAP.

Hope it helps.

**Comment by ngrafgr** [comment]
Yes, I noticed the problem with fungap environment. I am running this on a HPC and it was set up for me by the sys admin. My knowledge on that is pretty limited :( 
I re-ran the analysis, and it seems that fungap is calling the modules that were previously installed outside fungap environment correctly. We'll see if/where the run breaks next...

**Comment by mbnmbn00** [comment]
Hope it works!!!
Also, you can check `fungap.config` file to make sure which program you use.

**Comment by ngrafgr** [comment]
It worked almost all the way!! It broke at `wrapper_filter_gff3s`:
```
[06-14 21:25] START: wrapper_filter_gff3s
[Wrapper] python /opt/fungap/1.1.0/filter_gff3s.py --input_gff3s /home/nathalia/aus58/OUTPUT/augustus_out/augustus.gff3 /home/nathalia/aus58/OUTPUT/ma
ker_out/aus58/maker_aus58.gff3 /home/nathalia/aus58/OUTPUT/braker1_out/aus58/braker1_aus58.gff3 --mapping_file /home/nathalia/aus58/OUTPUT/gene_filter
ing/nr_prot_mapping.txt --blastp_dict /home/nathalia/aus58/OUTPUT/gene_filtering/blastp_score.p --busco_dict /home/nathalia/aus58/OUTPUT/gene_filterin
g/busco_score.p --pfam_dict /home/nathalia/aus58/OUTPUT/gene_filtering/pfam_score.p --blastn_dict /home/nathalia/aus58/OUTPUT/gene_filtering/blastn_sc
ore.p --bad_dict /home/nathalia/aus58/OUTPUT/gene_filtering/D_bad.p --nr_prot_file /home/nathalia/aus58/OUTPUT/gene_filtering/nr_prot.faa --output_dir
 /home/nathalia/aus58/OUTPUT/gene_filtering --log_dir /home/nathalia/aus58/OUTPUT/logs
/opt/fungap/anaconda/lib/python2.7/site-packages/scipy/sparse/lil.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility
. Expected 96, got 88
  from . import _csparsetools
/opt/fungap/anaconda/lib/python2.7/site-packages/scipy/spatial/__init__.py:94: RuntimeWarning: numpy.dtype size changed, may indicate binary incompati
bility. Expected 96, got 88
  from .ckdtree import *
/opt/fungap/anaconda/lib/python2.7/site-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompati
bility. Expected 96, got 88
  from .qhull import *
/opt/fungap/anaconda/lib/python2.7/site-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _voronoi
/opt/fungap/anaconda/lib/python2.7/site-packages/scipy/spatial/distance.py:121: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import _hausdorff
/opt/fungap/anaconda/lib/python2.7/site-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/opt/fungap/anaconda/lib/python2.7/site-packages/scipy/linalg/__init__.py:202: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/opt/fungap/anaconda/lib/python2.7/site-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
/opt/fungap/anaconda/lib/python2.7/site-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/opt/fungap/anaconda/lib/python2.7/site-packages/scipy/optimize/_trlib/__init__.py:1: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._trlib import TRLIBQuadraticSubproblem
/opt/fungap/anaconda/lib/python2.7/site-packages/scipy/optimize/_numdiff.py:8: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._group_columns import group_dense, group_sparse
usage: filter_gff3s.py -a <genome_assembly> -i <input_gff3s> -m <mapping_file> -b <blastp_dict> -B <busco_dict> -p <pfam_dict> -N <blastn_dict> -g <bad_dict> -n <nr_prot_file> -o <output_dir>
filter_gff3s.py: error: argument -a/--genome_assembly is required
Check input files...
TRANS_READ_FILES is ok...
GENOME_ASSEMBLY is ok...
SISTER_PROTEOME is ok...

Traceback (most recent call last):
  File "/opt/fungap/1.1.0/fungap.py", line 746, in <module>
    main(sys.argv[1:])
  File "/opt/fungap/1.1.0/fungap.py", line 268, in main
    nr_prot_file, nr_prot_mapping_file, output_dir
  File "/opt/fungap/1.1.0/fungap.py", line 691, in filter_gff3s
    check_call(command_args)
  File "/opt/fungap/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/opt/fungap/1.1.0/filter_gff3s.py', '--input_gff3s', '/home/nathalia/aus58/OUTPUT/augustus_out/augustus.gff3', '/home/nathalia/aus58/OUTPUT/maker_out/aus58/maker_aus58.gff3', '/home/nathalia/aus58/OUTPUT/braker1_out/aus58/braker1_aus58.gff3', '--mapping_file', '/home/nathalia/aus58/OUTPUT/gene_filtering/nr_prot_mapping.txt', '--blastp_dict', '/home/nathalia/aus58/OUTPUT/gene_filtering/blastp_score.p', '--busco_dict', '/home/nathalia/aus58/OUTPUT/gene_filtering/busco_score.p', '--pfam_dict', '/home/nathalia/aus58/OUTPUT/gene_filtering/pfam_score.p', '--blastn_dict', '/home/nathalia/aus58/OUTPUT/gene_filtering/blastn_score.p', '--bad_dict', '/home/nathalia/aus58/OUTPUT/gene_filtering/D_bad.p', '--nr_prot_file', '/home/nathalia/aus58/OUTPUT/gene_filtering/nr_prot.faa', '--output_dir', '/home/nathalia/aus58/OUTPUT/gene_filtering', '--log_dir', '/home/nathalia/aus58/OUTPUT/logs']' returned non-zero exit status 2
```

**Comment by mbnmbn00** [comment]
I think the wrapper code has a bug. For a quick fix for you,

```
python /opt/fungap/1.1.0/filter_gff3s.py \
  --input_gff3s /home/nathalia/aus58/OUTPUT/augustus_out/augustus.gff3 \
  /home/nathalia/aus58/OUTPUT/maker_out/aus58/maker_aus58.gff3 \
  /home/nathalia/aus58/OUTPUT/braker1_out/aus58/braker1_aus58.gff3 \
  --mapping_file /home/nathalia/aus58/OUTPUT/gene_filtering/nr_prot_mapping.txt \
  --blastp_dict /home/nathalia/aus58/OUTPUT/gene_filtering/blastp_score.p \
  --busco_dict /home/nathalia/aus58/OUTPUT/gene_filtering/busco_score.p \
  --pfam_dict /home/nathalia/aus58/OUTPUT/gene_filtering/pfam_score.p \
  --blastn_dict /home/nathalia/aus58/OUTPUT/gene_filtering/blastn_score.p \
  --bad_dict /home/nathalia/aus58/OUTPUT/gene_filtering/D_bad.p \
  --nr_prot_file /home/nathalia/aus58/OUTPUT/gene_filtering/nr_prot.faa \
  --output_dir /home/nathalia/aus58/OUTPUT/gene_filtering \
  --log_dir /home/nathalia/aus58/OUTPUT/logs
```

Please put your assembly file with `--genome_assembly` argument.
It will generate final output of GFF3 and PROT file.

While you get the output files of FunGAP, I will try to fix the issue.

**Comment by mbnmbn00** [comment]
Oh, I found that I've fixed this problem three months ago.
Install latest FunGAP codes should solve the problem, too!

(but this time, manually putting '--genome_assembly` argument seems safe)

**Comment by ngrafgr** [comment]
I git cloned the latest FunGAP, and the run ended successfully!! YAY!! **Thank you so much for your help!**

**Comment by mbnmbn00** [comment]
Glad to hear you finally finished. If you don't mind could you click the 'star' button for me? :)
Have a nice day!
