### ISSUE TITLE
Maker issue

### ISSUE THREAD

**Issue by Caro-Ca** [CompSynBioLab-KoreaUniv/FunGAP#22]
Hi Fungap!
I started installing Fungap from scratch and I keep having errors. Hope you could help me out. 
```
[Run] /home/edgar/anaconda2/envs/fungap/bin/maker -fix_nucleotides > /home/edgar/FunGAP/R18_annotation/logs/maker/maker_DRR111063_                       run4.log 2>&1
[09-23 03:54] DONE  training run3 & running maker run4
[Run] /home/edgar/anaconda2/envs/fungap/bin/gff3_merge -g -n -d /home/edgar/FunGAP/R18_annotation/maker_out/DRR111063/maker_run4/R                       18_CRRNanoimproved3.maker.output/R18_CRRNanoimproved3_master_datastore_index.log
[Run] /home/edgar/anaconda2/envs/fungap/bin/fasta_merge -d /home/edgar/FunGAP/R18_annotation/maker_out/DRR111063/maker_run4/R18_CR                       RNanoimproved3.maker.output/R18_CRRNanoimproved3_master_datastore_index.log
Traceback (most recent call last):
  File "/home/edgar/FunGAP/run_maker.py", line 647, in <module>
    main(sys.argv[1:])
  File "/home/edgar/FunGAP/run_maker.py", line 245, in main
    collect_result_final(input_fasta, output_dir, est_prefix)
  File "/home/edgar/FunGAP/run_maker.py", line 556, in collect_result_final
    copyfile(merged_faa, output_faa)
  File "/home/edgar/anaconda2/envs/fungap/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/edgar/FunGAP/R18_annotation/maker_out/DRR111063/maker_run4/R18_CRRNanoimprove                       d3.all.maker.proteins.fasta'
Traceback (most recent call last):
  File "fungap.py", line 746, in <module>
    main(sys.argv[1:])
  File "fungap.py", line 209, in main
    num_cores, repeat_model_file, trinity_asms, no_genemark_fungus
  File "fungap.py", line 397, in run_maker
    check_call(command_args)
  File "/home/edgar/anaconda2/envs/fungap/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/home/edgar/FunGAP/run_maker.py', '--input_fasta', '/home/edgar/FunGAP/R18_CRR                       Nanoimproved3.fa', '--augustus_species', 'Aspergillus_fumigatus', '--protein_db_fasta', '/home/edgar/FunGAP/prot_rosellinia_sister                       _org_db.faa', '--repeat_model', '/home/edgar/FunGAP/R18_annotation/repeat_modeler_out/RM_21510.ThuSep191500192019/consensi.fa.clas                       sified', '--est_files', '/home/edgar/FunGAP/R18_annotation/trinity_out/trinity_DRR111063/Trinity_DRR111063.fasta', '--output_dir',                        '/home/edgar/FunGAP/R18_annotation/maker_out', '--num_cores', '34', '--log_dir', '/home/edgar/FunGAP/R18_annotation/logs', '--gme                       s_fungus']' returned non-zero exit status 1

```

**Comment by Caro-Ca** [comment]
I found this error:

```
Could not find the config file /home/edgar/anaconda2/envs/fungap/config/species/Aspergillus_fumigatus/Aspergillus_fumigatus_parameters.cfg.
 Looking for Aspergillus_fumigatus_parameters.cfg in the configuration directory instead ... not found.

```
When I went to `/home/edgar/anaconda2/envs/fungap/config/species/` all ot them are on lower case letter. Should I delete maker 4 folder and start running the code again with: 

python fungap.py --output_dir R18_annotation/ -1 DRR111063_1.fastq -2 DRR111063_2.fastq --genome_assembly R18_CRRNanoimproved3.fa --augustus_species **aspergillus_fumigatus** --sister_proteome prot_rosellinia_sister_org_db.faa --num_cores 34

**Comment by mbnmbn00** [comment]
Changing to lower case help you?

**Comment by Caro-Ca** [comment]
So I found the error on maker 4. I deleted that folder and started to run the code with lower case letter for ausgustus_species. I am glad it ran perfectly! 

```
[09-24 06:51] DONE : Augustus
[09-24 06:51] DONE : wrapper_run_augustus

[09-24 06:51] START: wrapper_run_braker1
[Wrapper] python /home/edgar/FunGAP/run_braker1.py --masked_assembly /home/edgar/FunGAP/R18_annotation/maker_out/masked_assembly.fasta --bam_files /home/edgar/FunGAP/R18_annotation/hisat2_out/DRR111063.bam --output_dir /home/edgar/FunGAP/R18_annotation/braker1_out --log_dir /home/edgar/FunGAP/R18_annotation/logs --num_cores 34 --fungus
[09-24 06:51] START: BRAKER1
[Run] /home/edgar/anaconda2/envs/fungap/bin/braker.pl --fungus --softmasking --cores=34 --genome=/home/edgar/FunGAP/R18_annotation/maker_out/masked_assembly.fasta --bam=/home/edgar/FunGAP/R18_annotation/hisat2_out/DRR111063.bam --species=DRR111063 --gff3 --AUGUSTUS_CONFIG_PATH=/home/edgar/anaconda2/envs/fungap/bin/../config --BAMTOOLS_PATH=/home/edgar/anaconda2/envs/fungap/bin --GENEMARK_PATH=/home/edgar/FunGAP/external/gm_et_linux_64 --SAMTOOLS_PATH=/home/edgar/anaconda2/envs/fungap/bin --workingdir=/home/edgar/FunGAP/R18_annotation/braker1_out/DRR111063 > /home/edgar/FunGAP/R18_annotation/logs/braker1/braker1_DRR111063.log 2>&1
```

**Comment by mbnmbn00** [comment]
I'm so happy that you figured out the resolution!!
If you don't mind, could you click the "star button" for me?

Have a great day!
