### ISSUE TITLE
make_nr_prot step fails to process fasta files

### ISSUE THREAD

**Issue by Tierprot** [CompSynBioLab-KoreaUniv/FunGAP#31]
Pipeline fails to perform this step with this error:

Traceback (most recent call last):
  File "/workspace/FunGAP/make_nr_prot.py", line 96, in <module>
    main(sys.argv[1:])
  File "/workspace/FunGAP/make_nr_prot.py", line 35, in main
    make_nr_prot(faa_files, output_dir)
  File "/workspace/FunGAP/make_nr_prot.py", line 51, in make_nr_prot
    map = mmap.mmap(f.fileno(), 0, prot=mmap.PROT_READ)
mmap.error: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/workspace/FunGAP/fungap.py", line 746, in <module>
    main(sys.argv[1:])
  File "/workspace/FunGAP/fungap.py", line 233, in main
    nr_prot_file, nr_prot_mapping_file = make_nr_prot(faa_files, output_dir)
  File "/workspace/FunGAP/fungap.py", line 493, in make_nr_prot
    check_call(command_args)
  File "/opt/conda/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/workspace/FunGAP/make_nr_prot.py', '--faa_files', '/fungap_workspace/fungap_out/augustus_out/augustus.faa', '/fungap_workspace/fungap_out/maker_out/SRR5261647/maker_SRR5261647.faa', '/fungap_workspace/fungap_out/braker1_out/SRR5261647/braker1_SRR5261647.faa', '--output_dir', '/fungap_workspace/fungap_out/gene_filtering']' returned non-zero exit status 1

I have checked all 3 files - they do exists on provided  path and aren`t empty.

**Comment by Tierprot** [comment]
Simple modification of the part solves the problem:

with open(faa_file, 'r+b') as f:
        map = mmap.mmap(f.fileno(), 0, prot=mmap.PROT_READ)
         for line in iter(map.readline, ''):
