### ISSUE TITLE
fungap.conf file not found.

### ISSUE THREAD

**Issue by Lamm-a** [CompSynBioLab-KoreaUniv/FunGAP#62]
**Error message**
```
============ New Run 2021-02-10 11:56:42.818392 ============
Traceback (most recent call last):
  File "/services/tools/fungap/1.1.1/fungap.py", line 838, in <module>
    main()
  File "/services/tools/fungap/1.1.1/fungap.py", line 181, in main
    genome_assembly, sister_proteome, busco_dataset
  File "/services/tools/fungap/1.1.1/check_inputs.py", line 29, in check_inputs
    check_busco_dataset(busco_dataset)
  File "/services/tools/fungap/1.1.1/check_inputs.py", line 157, in check_busco_dataset
    d_conf = import_config()
  File "/services/tools/fungap/1.1.1/import_config.py", line 12, in import_config
    with open(config_file) as f_in:
FileNotFoundError: [Errno 2] No such file or directory: '/services/tools/fungap/1.1.1/fungap.conf'
```
When running FunGAP all attempts are returning with this error.

I contacted our Sys admin and they said it is likely usage issue so I am posting here.

What would be causing this error and is it something I am doing wrong?

**Command**
`
fungap.py --output_dir  $outdir --trans_read_1 $rFwd --trans_read_2 $rRvs --genome_assembly $assembly --augustus_species $augSpecies --busco_dataset $busco --sister_proteome $sisProtDB`

**Version**
`fungap/1.1.1`

**Comment by mbnmbn00** [comment]
Hello,

FunGAP is trying to find configure file.
```
/services/tools/fungap/1.1.1/fungap.conf
```

You can generate the file by following the below. Hope it resolves your issue.

## 6. Configure FunGAP
This script allows users to set and test (by `--help` command) all the dependencies. If this script runs without any issue, you are ready to run FunGAP!

```
cd $FUNGAP_DIR
conda activate maker
export MAKER_DIR=$(dirname $(which maker))
echo $MAKER_DIR  # /home/ubuntu/anaconda3/envs/maker/bin
conda activate fungap
./set_dependencies.py \
  --pfam_db_path db/pfam/ \
  --genemark_path external/gmes_linux_64/ \
  --maker_path ${MAKER_DIR}
```

**Comment by Lamm-a** [comment]
Hey,

I contacted our sys admin and they said the following:
```

FunGAP is installed in a shared Conda environment, which works for numerous other applications btw, and I ran "./set_dependencies.py" during installation (it's also included in the install "guide"), but it fails to create fungap.conf due to several "secret" (and wrong/incomplete) dependencies _only_ listed inside the python script AND location errors, ex.
...
$ ./set_dependencies.py --pfam_db_path db/pfam/ --genemark_path ${GENEMARK_PATH} --maker_path ${MAKER_DIR}
 
** Checking the installed locations of dependencies **
 
[GeneMark path] /services/tools/genemark-es/4.46/gmes_petap.pl
[GeneMark path] /services/tools/genemark-es/4.46/gmhmme3
[GeneMark path] /services/tools/genemark-es/4.46/probuild
[Hisat2 path] /services/tools/hisat2/2.2.1/hisat2
[Trinity path] /services/tools/trinityrnaseq/2.9.1/Trinity
[Maker path] /services/tools/maker/2.31.11/bin/maker
[Maker path] /services/tools/maker/2.31.11/bin/gff3_merge
[Maker path] /services/tools/maker/2.31.11/bin/fasta_merge
[Maker path] /services/tools/maker/2.31.11/bin/maker2zff
[ERROR] No installation of Snap found. "fathom" should be located in the /services/tools/maker/2.31.11/bin directory
$ which fathom
/services/tools/korflab/snap/20131129/fathom
```

Their advice is the only way to run FunGAP would be in my own conda environment.

**Comment by Lamm-a** [comment]
Is it possible to get a fix on this as fathom in not part of MAKER.

It looks like an error in 'set_dependencies.py' that is expecting this to be the case?

**Comment by mbnmbn00** [comment]
Sorry for the late response.
If you install the Maker with **Conda** `fathom` will be in the directory where the maker is located.

Suggestion 1
```
cd /services/tools/maker/2.31.11/bin
ln -s /services/tools/korflab/snap/20131129/fathom .
```

* Then run the `set_dependencies.py` again.

Suggestion 2

* If you can use conda, that's  the best/easiest option
```
conda create -n maker -c bioconda maker=2.31.10
```
