### ISSUE TITLE
[ERROR] You provided wrong BAM FILES. when using fungap.py

### ISSUE THREAD

**Issue by Lamm-a** [CompSynBioLab-KoreaUniv/FunGAP#64]
I am getting this error when running `fungap.py`. I am not providing any BAMs as I thought the tool generated them itself with hisat?

```
============ New Run 2021-02-19 17:27:47.819526 ============
[02-19 17:27] START: wrapper_run_hisat2
[Wrapper] /home/projects/ku_00014/people/robmur/programmes/FunGAP/run_hisat2.py --read_files /home/people/robmur/people/suzsch/termitomyces/RNA/P5_RNA_2020/RNA_used/Q30_trimmedReads/P5_1.fastq /home/people/robmur/people/suzsch/termitomyces/RNA/P5_RNA_2020/RNA_used/Q30_trimmedReads/P5_2.fastq --output_dir /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/hisat2_out --log_dir /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/logs --ref_fasta /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/Micro_sorted.fasta --num_cores 1 --max_intron 2000
[02-19 17:27] START: Hisat2
[Run] /services/tools/hisat2/2.2.1/hisat2-build -p 1 /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/Micro_sorted.fasta /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/Micro_sorted.fasta > /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/logs/hisat2-build.log 2>&1
[Run] /services/tools/hisat2/2.2.1/hisat2 --max-intronlen 2000 -p 1 -x /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/Micro_sorted.fasta -1 /home/people/robmur/people/suzsch/termitomyces/RNA/P5_RNA_2020/RNA_used/Q30_trimmedReads/P5_1.fastq -2 /home/people/robmur/people/suzsch/termitomyces/RNA/P5_RNA_2020/RNA_used/Q30_trimmedReads/P5_2.fastq 2> /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/logs/hisat2_P5.log | /home/projects/ku_00014/people/robmur/programmes/miniconda3/envs/fungap/bin/samtools view -bSF4 - | /home/projects/ku_00014/people/robmur/programmes/miniconda3/envs/fungap/bin/samtools sort - -o /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/hisat2_out/P5.bam
[main_samview] fail to read the header from "-".
samtools sort: failed to read header from "-"
[02-19 17:27] DONE : Hisat2
[02-19 17:27] DONE : wrapper_run_hisat2

[02-19 17:27] START: wrapper_run_trinity
[Wrapper] /home/projects/ku_00014/people/robmur/programmes/FunGAP/run_trinity.py --bam_files /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/hisat2_out/P5.bam --output_dir /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/trinity_out --log_dir /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/logs --num_cores 1 --max_intron 2000 --jaccard_clip
[ERROR] You provided wrong BAM FILES. Please check
Traceback (most recent call last):
  File "/home/people/robmur/robmur/programmes/FunGAP/fungap.py", line 838, in <module>
    main()
  File "/home/people/robmur/robmur/programmes/FunGAP/fungap.py", line 187, in main
    trinity_asms = run_trinity(
  File "/home/people/robmur/robmur/programmes/FunGAP/fungap.py", line 392, in run_trinity
    check_call(command_args)
  File "/home/projects/ku_00014/people/robmur/programmes/miniconda3/envs/fungap/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/projects/ku_00014/people/robmur/programmes/FunGAP/run_trinity.py', '--bam_files', '/home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/hisat2_out/P5.bam', '--output_dir', '/home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/trinity_out', '--log_dir', '/home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/logs', '--num_cores', '1', '--max_intron', '2000', '--jaccard_clip']' returned non-zero exit status 2.
```

Any advice would be aprociated :)

**Comment by mbnmbn00** [comment]
It seems HISAT failed to run.
Can you show me the output of:
```
/home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/logs/hisat2-build.log
```
and
```
/home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/logs/hisat2_P5.log
```

Also, could you run the below command to see if it gives an error?
```
/services/tools/hisat2/2.2.1/hisat2 --help
```

**Comment by Lamm-a** [comment]
Hi there,

So I have tried hisat2 installed both through conda and a local install and get the same issues:

```
less /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/logs/hisat2-build.log

hisat2-build: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by hisat2-build)
hisat2-build: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by hisat2-build)
hisat2-build: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by hisat2-build)
```
I solved this with adding the gcc module and hisat seems to work fine now. However trinity has some problem:

```
============ New Run 2021-02-22 13:43:08.304191 ============
[02-22 13:43] START: wrapper_run_hisat2
[Wrapper] /home/projects/ku_00014/people/robmur/programmes/FunGAP/run_hisat2.py --read_files /home/people/robmur/people/suzsch/termitomyces/RNA/P5_RNA_2020/RNA_used/Q30_trimmedReads/P5_1.fastq /home/people/robmur/people/suzsch/termitomyces/RNA/P5_RNA_2020/RNA_used/Q30_trimmedReads/P5_2.fastq --output_dir /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/hisat2_out --log_dir /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/logs --ref_fasta /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/PseudaA_sorted.fasta --num_cores 1 --max_intron 2000
[02-22 13:43] START: Hisat2
[Note] Running hisat2-build has already been finished
[Run] /services/tools/hisat2/2.2.1/hisat2 --max-intronlen 2000 -p 1 -x /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/PseudaA_sorted.fasta -1 /home/people/robmur/people/suzsch/termitomyces/RNA/P5_RNA_2020/RNA_used/Q30_trimmedReads/P5_1.fastq -2 /home/people/robmur/people/suzsch/termitomyces/RNA/P5_RNA_2020/RNA_used/Q30_trimmedReads/P5_2.fastq 2> /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/logs/hisat2_P5.log | /home/projects/ku_00014/people/robmur/programmes/miniconda3/envs/fungap/bin/samtools view -bSF4 - | /home/projects/ku_00014/people/robmur/programmes/miniconda3/envs/fungap/bin/samtools sort - -o /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/hisat2_out/P5.bam
[02-22 13:52] DONE : Hisat2
[02-22 13:52] DONE : wrapper_run_hisat2

[02-22 13:52] START: wrapper_run_trinity
[Wrapper] /home/projects/ku_00014/people/robmur/programmes/FunGAP/run_trinity.py --bam_files /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/hisat2_out/P5.bam --output_dir /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/trinity_out --log_dir /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/logs --num_cores 1 --max_intron 2000 --jaccard_clip
[02-22 13:52] START: Trinity for P5
[Run] /home/projects/ku_00014/people/robmur/programmes/miniconda3/envs/fungap/bin/Trinity --jaccard_clip --genome_guided_bam /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/hisat2_out/P5.bam --genome_guided_max_intron 2000 --max_memory 10G --CPU 1 --output /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/trinity_out/trinity_P5 > /home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/logs/trinity_P5.log 2>&1
Traceback (most recent call last):
  File "/home/projects/ku_00014/people/robmur/programmes/FunGAP/run_trinity.py", line 160, in <module>
    main()
  File "/home/projects/ku_00014/people/robmur/programmes/FunGAP/run_trinity.py", line 97, in main
    run_trinity(
  File "/home/projects/ku_00014/people/robmur/programmes/FunGAP/run_trinity.py", line 149, in run_trinity
    os.rename(trinity_output, new_output)
FileNotFoundError: [Errno 2] No such file or directory: '/home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/trinity_out/trinity_P5/Trinity-GG.fasta' -> '/home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/trinity_out/trinity_P5/Trinity_P5.fasta'
Traceback (most recent call last):
  File "/home/people/robmur/robmur/programmes/FunGAP/fungap.py", line 838, in <module>
    main()
  File "/home/people/robmur/robmur/programmes/FunGAP/fungap.py", line 187, in main
    trinity_asms = run_trinity(
  File "/home/people/robmur/robmur/programmes/FunGAP/fungap.py", line 392, in run_trinity
    check_call(command_args)
  File "/home/projects/ku_00014/people/robmur/programmes/miniconda3/envs/fungap/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/projects/ku_00014/people/robmur/programmes/FunGAP/run_trinity.py', '--bam_files', '/home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/hisat2_out/P5.bam', '--output_dir', '/home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/trinity_out', '--log_dir', '/home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/logs', '--num_cores', '1', '--max_intron', '2000', '--jaccard_clip']' returned non-zero exit status 1.
```

**Comment by Lamm-a** [comment]
Any idea what would be causing these trinity problems?

**Comment by mbnmbn00** [comment]
So sorry, I was so busy last week.
Can you shoe me the output of:
```
/home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/logs/trinity_P5.log
```

Also, seeing the Hisat2 log would be helpful:
```
/home/people/robmur/people/suzsch/termitomyces/assemblies_final/q30_ref/all_fasta/sorted/fungap_output/PseudaA_sorted/logs/hisat2_P5.log
```

**Comment by Lamm-a** [comment]
No worries!

Here is the `trinity` log.
[trinity_P5.zip](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/6051717/trinity_P5.zip)

Here is the `hisat2 `logs.
[hisat2_P5.zip](https://github.com/CompSynBioLab-KoreaUniv/FunGAP/files/6051719/hisat2_P5.zip)

**Comment by mbnmbn00** [comment]
Okay.

```
22388974 reads; of these:
  22388974 (100.00%) were paired; of these:
    22198496 (99.15%) aligned concordantly 0 times
    186340 (0.83%) aligned concordantly exactly 1 time
    4138 (0.02%) aligned concordantly >1 times
    ----
    22198496 pairs aligned concordantly 0 times; of these:
      14417 (0.06%) aligned discordantly 1 time
    ----
    22184079 pairs aligned 0 times concordantly or discordantly; of these:
      44368158 mates make up the pairs; of these:
        43893988 (98.93%) aligned 0 times
        440965 (0.99%) aligned exactly 1 time
        33205 (0.07%) aligned >1 times
1.97% overall alignment rate
```
Only 2% of reads were mapped. It seems you used totally different organism's RNA-seq.
Can you double-check your RNA-seq file??

**Comment by Lamm-a** [comment]
After double checking they are indeed the same species. We know they are different strains, but a mapping rate of 2% is crazy! I tried to map with `bowtie2` and only 8-9% also.

I wonder what could be causing this!

**Comment by mbnmbn00** [comment]
Yes. If the alignment rate is ~2%, it is unlikely to assemble the transcriptome properly.

1) Where did you get the RNA-seq? (from your sample? NCBI? or MycoCosm?)
2) What's your organism? You might try other RNA-seq data.

Since it's a public discussion, you can send me an e-mail at mbnmbn00@gmail.com.

If you got the RNA-seq from your own experiment, you may try to assemble the transcriptome and calculate the percent identity between your genome and transcriptome.

Hope I can help you more.

**Comment by mbnmbn00** [comment]
I'm closing this issue now, please re-open whenever you want.
