### ISSUE TITLE
Biopython problems

### ISSUE THREAD

**Issue by Hoberti** [CompSynBioLab-KoreaUniv/FunGAP#80]
Hi,

I find this when I run run_braker

getAnnoFastaFromJoingenes.py -g maker_out/masked_assembly.fasta.adjusted -o braker_out/308/braker_308 -t 1 -3 braker_out/308/braker_308.gff3

anaconda3/envs/fungap/bin/getAnnoFastaFromJoingenes.py
Traceback (most recent call last):
  File "/anaconda3/envs/FUNGAP/bin/getAnnoFastaFromJoingenes.py", line 35, in <module>
    from Bio.Alphabet import generic_dna, generic_protein
  File "anaconda3/envs/FUNGAP/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "anaconda3/envs/FUNGAP/bin/getAnnoFastaFromJoingenes.py", line 39, in <module>
    raise ImportError(
ImportError: Failed to import biophython modules. Try installing with "pip3 install biopython"

I find that biopython==1.79 has no more the Bio.Alphabet module, this could easily solucionated when installing biopython with pip: pip install  biopython==1.75

Is this correct?

Héctor

**Comment by mbnmbn00** [comment]
Hello,

Which Braker and Augustus versions are you using?

```
braker.pl --version
braker.pl version 2.1.5
```
```
augustus --version
AUGUSTUS (3.4.0) is a gene prediction tool.
Sources and documentation at https://github.com/Gaius-Augustus/Augustus
```

In my `/home/ubuntu/anaconda3/envs/fungap/bin/getAnnoFastaFromJoingenes.py` script, there's no `Bio.Alphabet`.
