### ISSUE TITLE
Issue with wrapper_create_markdown

### ISSUE THREAD

**Issue by ehsansari1234** [CompSynBioLab-KoreaUniv/FunGAP#90]
Hi.

I have installed a conda version of FunGAP on my shared system to which I do not have root privilege. All steps went well until the create_markdown when loading matplotlib leads to "ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found" error. My system glibc version is 30, the reason it is probably complaining."

here is the log:{{
[12-15 00:57] START: wrapper_create_markdown
[Wrapper] /gpfs/mdiops/opal/opal_wheat/users/ehs220/src2/FunGAP/create_markdown.py --input_fasta /gpfs/mdiops/opal/opal_wheat/users/eh>
Traceback (most recent call last):
  File "/gpfs/mdiops/opal/opal_wheat/users/ehs220/src2/FunGAP/create_markdown.py", line 16, in <module>
    import matplotlib as mpl
  File "/globalhome/ehs220/HPC/scratch/src2/miniconda3/envs/fungap/lib/python3.7/site-packages/matplotlib/__init__.py", line 107, in <>
    from . import _api, cbook, docstring, rcsetup
  File "/globalhome/ehs220/HPC/scratch/src2/miniconda3/envs/fungap/lib/python3.7/site-packages/matplotlib/rcsetup.py", line 26, in <mo>
    from matplotlib.colors import Colormap, is_color_like
  File "/globalhome/ehs220/HPC/scratch/src2/miniconda3/envs/fungap/lib/python3.7/site-packages/matplotlib/colors.py", line 82, in <mod>
    from matplotlib import _api, cbook, scale
  File "/globalhome/ehs220/HPC/scratch/src2/miniconda3/envs/fungap/lib/python3.7/site-packages/matplotlib/scale.py", line 18, in <modu>
    from matplotlib.ticker import (
  File "/globalhome/ehs220/HPC/scratch/src2/miniconda3/envs/fungap/lib/python3.7/site-packages/matplotlib/ticker.py", line 179, in <mo>
    from matplotlib import transforms as mtransforms
  File "/globalhome/ehs220/HPC/scratch/src2/miniconda3/envs/fungap/lib/python3.7/site-packages/matplotlib/transforms.py", line 46, in >
    from matplotlib._path import (
ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /globalhome/ehs220/HPC/scratch/src2/miniconda3/envs/fungap/>
Check input files...
TRANS_READ_FILES is ok...
GENOME_ASSEMBLY is ok...
SISTER_PROTEOME is ok...
BUSCO_DATASET is ok...

Traceback (most recent call last):
  File "/gpfs/mdiops/opal/opal_wheat/users/ehs220/src2/FunGAP/fungap.py", line 839, in <module>
    main()
  File "/gpfs/mdiops/opal/opal_wheat/users/ehs220/src2/FunGAP/fungap.py", line 281, in main
    genome_assembly, output_dir, trans_bams, trinity_asms, d_path, logger
  File "/gpfs/mdiops/opal/opal_wheat/users/ehs220/src2/FunGAP/fungap.py", line 832, in create_markdown
    check_call(command_args)
  File "/globalhome/ehs220/HPC/scratch/src2/miniconda3/envs/fungap/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/gpfs/mdiops/opal/opal_wheat/users/ehs220/src2/FunGAP/create_markdown.py', '--input_fasta', }}

here is the ldd version of my system:

{{ldd --version
dd (Gentoo 2.30-r8 p10) 2.30
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.}}

I tried to install a local glibc 2.29 library and use it with LD_LIBRARY_PATH but it complains about discrepancy between system and local library. 

Is there any solution for this or is there anyway to have a local Glibc in conda so the fungap.py wont's use my machine glibc library. I am not professional in managing linux machine so sorry if I am missing a big point here. Should you require further info from my side, please let me know.

**Comment by mbnmbn00** [comment]
`import matplotlib as mpl` is the cause of the error.
Have you ever used the `matplotlib` on your server?

Can you test
```
python3
>>> import matplotlib
```

If you don't have `matplotlib` already,
```
conda create -n matplotlib -c conda-forge matplotlib
conda activate matplotlib
python3
>>> import matplotlib
```

It would be a good start to resolve the issue.

**Comment by ehsansari1234** [comment]
I installed matplotlib in my conda env and it worked. Thanks for your help.

**Comment by mbnmbn00** [comment]
If you don't mind, could you click the "star button" at the top?
It will help get more attention of this program from researchers.
